<a href="https://colab.research.google.com/github/Hyungu0211/Branch-Repository/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn

#GPU 사용 설정
device = 'cuda' if torch.cuda.is_available() else 'cpu'

#Random 함수 사용을 위한 seed value 설정
torch.manual_seed(2022)
if device == 'cuda':
    torch.cuda.manual_seed_all(2022)
#학습 데이터 설정(X: Input tensors, Y: Output tensors,FloatTensor: 자료형이 float인 tensor를 생성)
X = torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]]).to(device)
Y = torch.FloatTensor([[0],[1],[1],[1]]).to(device)
#Perceptron의 연결 구조 설정
model = nn.Sequential(nn.Linear(2,1,bias=True), nn.Sigmoid()).to(device)
#손실 함수와 학습 알고리즘 설정
loss_func = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
#perceptron 학습
for step in range(20001):
    optimizer.zero_grad()

    Y_hat = model(X)
    loss = loss_func(Y_hat, Y)
    loss.backward()
    optimizer.step()

    if step % 1000== 0:
        print(step, loss.item())
#학습된 Perceptron 테스트
    with torch.no_grad():
        model.eval()
        inputs = torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]]).to(device)
        outputs = model(inputs)

        print(outputs)
        print(outputs >0.5)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([[0.1041],
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([[0.1041],
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([[0.1041],
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([[0.1041],
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([[0.1041],
        [0.9591],
        [0.9585],
        [0.9998]], device='cuda:0')
tensor([[Fal